from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field


class OHLCVBar(BaseModel):
    timestamp: datetime = Field(..., description="Bar opening UTC timestamp")
    open: float = Field(..., description="Open price")
    high: float = Field(..., description="High price")
    low: float = Field(..., description="Low price")
    close: float = Field(..., description="Close price")
    volume: int = Field(..., description="Traded volume")


class MarketQuote(BaseModel):
    symbol: str = Field(..., description="Ticker symbol")
    price: float = Field(..., description="Latest traded price")
    change: float = Field(..., description="Daily nominal price change")
    change_pct: float = Field(..., description="Daily percentage change")
    open: float = Field(..., description="Session open price")
    high_24h: float = Field(..., description="Session high price")
    low_24h: float = Field(..., description="Session low price")
    volume: int = Field(..., description="Accumulated session volume")
    timestamp: datetime = Field(..., description="Quote timestamp")
    is_demo: bool = Field(True, description="True if generated by mock provider")


class SymbolInfo(BaseModel):
    symbol: str
    name: str
    exchange: str
    asset_class: str
    current_price: float
    daily_change_pct: float
    is_demo: bool = True


class HistoricalDataResponse(BaseModel):
    symbol: str
    timeframe: str
    count: int
    bars: List[OHLCVBar]
    is_demo: bool = True
